name: Data issue in the App
description: Submit an issue with the data provided in the app. (Broken links, new modules, ...)
title: "[Problem with module data]: "
labels: ["bug"]
assignees:
  - AlexRomberg
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to help keeping the site up to date!
  - type: input
    id: module
    attributes:
      label: Affected Module
      description: On which module/modules does the issue happen?
      placeholder: ex. ANA-G
    validations:
      required: true
  - type: textarea
    id: issue
    attributes:
      label: What is the issue?
      description: Also tell us, what did you expect to be there?
      placeholder: ex. Link is broken, is now ...
    validations:
      required: true
